##remote_theme: pages-themes/architect@v0.2.0
##plugins:
##- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Aerospace Engineering: Sensors and Automation Systems for Sustainable Space Agriculture"
description: "A professional research paper on space agriculture"
theme: minima

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

# Minima theme customization
minima:
  skin: dark # Choose 'dark', 'light', or 'default' as your color scheme

# Social Links
social_links:
  github: https://github.com/MakaylaLundry

# Optional: Add other configurations, like baseurl or permalink settings, if needed
